In [13]:
#import modules
import json
import pandas as pd
from binance.client import Client
from dotenv import load_dotenv
from envs import env
import time
import re
import os
import datetime
from datetime import timedelta
import statistics
import numpy as np
from scipy.stats import kurtosis, skew

In [14]:
#import classes from ./ folder
import postgresdbAccess

In [15]:
#read fibonacci retracements  from json
with open('fibLvl.json') as file:
    fibLvl = json.load(file)

In [16]:
def writeTrade(openPositions, row, postgres):
    openPositions['resultPercent'] = (((row[4] - 
        openPositions['askPrice']) / openPositions['askPrice']) * 
        100 - brokerFees * 2.55)
    openPositions['stopId'] = row[0]        
    closeSql = ("UPDATE " + dbTable + " SET" +
        " startId = '" + str(int(openPositions['startId'])) +
        "', fibLevel = '" + str(openPositions['fibLevel']) +
        "', midId = '" + str(int(openPositions['id'])) +
        "', corValue = '" + str(openPositions['corValue']) +
        "', takeProfit = '" + str(openPositions['takeProfit']) +
        "', stopLoss = '" + str(openPositions['stopLoss']) +  
        "', resultpercent = '" + str(openPositions['resultPercent']) +
        "', stopid = '" + str(openPositions['stopId']) +
        "', skew = '" + str(openPositions['skew']) +
        "', kurtosis = '" + str(openPositions['kurtosis']) +
        "' WHERE id = '" + str(int(openPositions['id'])) +
        "';")
    postgres.sqlUpdate(closeSql)

In [17]:
def backtest():
    #initiate empty open positions
    openPositions = {}
    #initiate postgresdb class
    postgres = postgresdbAccess.postgresAccess()
    #get unique simbol list
    sql = ("SELECT distinct symbol FROM " + dbTable + ";")
    uniqueSymbol = pd.DataFrame(postgres.sqlQuery(sql))
    uniqueSymbol = uniqueSymbol[0]
    #initiate empty percent bar
    percentBar = 0
    #loop over every symbol in symbol list
    for symbol in uniqueSymbol:
        #print progress
        print(percentBar, " / ", len(uniqueSymbol))
        percentBar = percentBar + 1
        #skip if symbol is not to be considered
        #null askprice is sorted out with crawler already
        if not (symbol.endswith(baseCurrency) and
               len(symbol) < 11):
            continue
        #check if open position was left over from last symbol and simulate close
        if openPositions:
            writeTrade(openPositions, row, postgres)
            openPositions = {}
        #query for every line for symbol
        sql = ("SELECT id, time, symbol, askprice, " +
               "bidprice, highprice, quotevolume, " +
               "pricechangepercent, weightedavgprice, openprice" +
            " FROM " + dbTable + " WHERE" +
            " symbol like '" + symbol + "' order by id;")
        print(sql)
        bigData = pd.DataFrame(postgres.sqlQuery(sql))
        bigData[0] = pd.to_numeric(bigData[0], errors='coerce', downcast='float')
        bigData[1] = pd.to_datetime(bigData[1])
        bigData[3] = pd.to_numeric(bigData[3], errors='coerce', downcast='float')
        bigData[4] = pd.to_numeric(bigData[4], errors='coerce', downcast='float')
        bigData[6] = pd.to_numeric(bigData[6], errors='coerce', downcast='float')
        bigData[7] = pd.to_numeric(bigData[7], errors='coerce', downcast='float')
        bigData[8] = pd.to_numeric(bigData[8], errors='coerce', downcast='float')
        bigData[9] = pd.to_numeric(bigData[9], errors='coerce', downcast='float')
        #get start of timedelta
        bigData[5] = bigData[1] - timedelta(hours=33)
        bigData[10] = bigData[1] - timedelta(hours=22)
        bigData[11] = bigData[1] - timedelta(hours=11)
        #loop over every row
        for index, row in bigData.iterrows():
            before_start_date = bigData[1] <= row[5]
            if len(bigData.loc[before_start_date]) > 0:
                #get data for consideration
                after_start_date = bigData[1] >= row[5]
                before_end_date = bigData[1] <= row[1]
                between_two_dates = after_start_date & before_end_date
                fibDates = bigData.loc[between_two_dates]
                diff = fibDates[3].max() - fibDates[3].min()
                # calculate fibRetracements
                fibRetracement = pd.DataFrame(fibLvl)
                maxAsk = fibDates[3].max()
                for lvl in fibRetracement:
                    fibRetracement[1] =  maxAsk - diff * fibRetracement[0]
                    fibRetracement[2] = fibRetracement[1] * 0.9995
                    fibRetracement[3] = fibRetracement[1] * 1.0005
                #calculate corvalue
                corValue = fibDates[0].corr(fibDates[3])
                before_start_date1 = bigData[1] <= row[5]
                bigData[10] = bigData[1] - timedelta(hours=15)
                after_start_date1 = bigData[1] >= row[10]
                before_end_date1 = bigData[1] <= row[1]
                between_two_dates1 = after_start_date1 & before_end_date1
                fibDates1 = bigData.loc[between_two_dates]
                corValue1 = fibDates1[0].corr(fibDates1[3])
                
                before_start_date2 = bigData[1] <= row[5]
                bigData[11] = bigData[1] - timedelta(hours=5)
                after_start_date2 = bigData[1] >= row[11]
                before_end_date2 = bigData[1] <= row[1]
                between_two_dates2 = after_start_date2 & before_end_date2
                fibDates2 = bigData.loc[between_two_dates2]
                corValue2 = fibDates2[0].corr(fibDates2[3])
                
                #get statistical parameters
                statisticsTools = {}
                statisticsTools["stDev"] = statistics.stdev(fibDates[3])
                statisticsTools["skew"] = skew(fibDates[3])
                statisticsTools["kurtosis"] = kurtosis(fibDates[3])
                
                #if an open position exists, check if it can be closed
                if openPositions:
                    if (row[3] < openPositions['stopLoss'] or
                        row[3] > openPositions['takeProfit']):
                        writeTrade(openPositions, row, postgres)
                        #clear open position
                        openPositions = {}
                else:
                    #loop over considered fibonacciretracements
                    for i in [7]:
                        #check if buy requirements are met
                        if (corValue >= 0 and
                            corValue1 >= 0 and
                            corValue2 >= 0 and
                            row[3] < fibRetracement[3][i] and
                            row[3] > fibRetracement[2][i]):
                            openPositions['startId'] = fibDates[0].min()
                            openPositions['id'] = row[0]
                            openPositions['bidPrice'] = row[4]
                            openPositions['fibLevel'] = i
                            openPositions['symbol'] = symbol
                            openPositions['askPrice'] = row[3]
                            openPositions['corValue'] = corValue
                            openPositions['stDev'] = statisticsTools["stDev"]
                            openPositions['skew'] = statisticsTools["skew"]
                            openPositions['kurtosis'] = statisticsTools["kurtosis"]
                            openPositions['takeProfit'] = fibRetracement[3][i+4]
                            openPositions['stopLoss'] = fibRetracement[2][i-1]
    #close database connection
    postgres.databaseClose()

In [ ]:
testTables = [{"table":"backtesting","currency":"BNB"},
             {"table":"backtesting","currency":"BTC"},
             {"table":"backtesting","currency":"ETH"},
             {"table":"backtesting","currency":"ADA"}]
for iteration in testTables:
    load_dotenv('../.env')
    try:
        liveVolume=env("liveVolume")
        apiSecret=env('apiSecret')
        apiKey=env('apiKey')
        dbTable=iteration["table"]
        baseCurrency=iteration["currency"]
        brokerFees=float(env('brokerFees'))
        liveTrading=env("liveTrading", 'False').lower() in ('true', '1', 't')
    except KeyError:
        print("No env variables set.")
        sys.exit(1)
    client = Client(apiKey, apiSecret, {'timeout':600})
    backtest()

0  /  752
1  /  752
2  /  752
3  /  752
4  /  752
5  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ADXBNB' order by id;
6  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ENJBNB' order by id;
7  /  752
8  /  752
9  /  752
10  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CNDBNB' order by id;
11  /  752
12  /  752
13  /  752
14  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WANBNB' order by id;
15  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RDNBNB' order by id;
16  /  752
17  /  752
18  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'YOYOBNB' order by id;
19  /  752
20  /  752
21  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'IOSTBNB' order by id;
22  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FTTBNB' order by id;
23  /  752
24  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'OCEANBNB' order by id;
25  /  752
26  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'COMPBNB' order by id;
27  /  752
28  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BCPTBNB' order by id;
29  /  752
30  /  752
31  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BONDBNB' order by id;
32  /  752
33  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'UNFIBNB' order by id;
34  /  752
35  /  752
36  /  752
37  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NEBLBNB' order by id;
38  /  752
39  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ICPBNB' order by id;
40  /  752
41  /  752
42  /  752
43  /  752
44  /  752
45  /  752
46  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PAXBNB' order by id;
47  /  752
48  /  752
49  /  752
50  /  752
51  /  752
52  /  752
53  /  752
54  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DASHBNB' order by id;
55  /  752
56  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FLOWBNB' order by id;
57  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PIVXBNB' order by id;
58  /  752
59  /  752
60  /  752
61  /  752
62  /  752
63  /  752
64  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TOMOBNB' order by id;
65  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WAVESBNB' order by id;
66  /  752
67  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'EOSBNB' order by id;
68  /  752
69  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'LPTBNB' order by id;
70  /  752
71  /  752
72  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SPARTABNB' order by id;
73  /  752
74  /  752
75  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'THETABNB' order by id;
76  /  752
77  /  752
78  /  752
79  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'QNTBNB' order by id;
80  /  752
81  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SXPBNB' order by id;
82  /  752
83  /  752
84  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'VETBNB' order by id;
85  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'IOTABNB' order by id;
86  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BTSBNB' order by id;
87  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'GOBNB' order by id;
88  /  752
89  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SCBNB' order by id;
90  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DUSKBNB' order by id;
91  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ERDBNB' order by id;
92  /  752
93  /  752
94  /  752
95  /  752
96  /  752
97  /  752
98  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ZILBNB' order by id;
99  /  752
100  /  752
101  /  752
102  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PHXBNB' order by id;
103  /  752
104  /  752
105  /  752
106  /  752
107  /  752
108  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CHRBNB' order by id;
109  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'STPTBNB' order by id;
110  /  752
111  /  752
112  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'EGLDBNB' order by id;
113  /  752
114  /  752
115  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BCCBNB' order by id;

116  /  752
117  /  752
118  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CVCBNB' order by id;
119  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TORNBNB' order by id;
120  /  752
121  /  752
122  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XVSBNB' order by id;
123  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FLMBNB' order by id;
124  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MLNBNB' order by id;
125  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SWRVBNB' order by id;
126  /  752
127  /  752
128  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DOTBNB' order by id;
129  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'GNTBNB' order by id;
130  /  752
131  /  752
132  /  752
133  /  752
134  /  752
135  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PHBBNB' order by id;
136  /  752
137  /  752
138  /  752
139  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WABIBNB' order by id;
140  /  752
141  /  752
142  /  752
143  /  752
144  /  752
145  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ONEBNB' order by id;
146  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'HARDBNB' order by id;
147  /  752
148  /  752
149  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FARMBNB' order by id;
150  /  752
151  /  752
152  /  752
153  /  752
154  /  752
155  /  752
156  /  752
157  /  752
158  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BCNBNB' order by id;
159  /  752
160  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'STRATBNB' order by id;
161  /  752
162  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'VIABNB' order by id;
163  /  752
164  /  752
165  /  752
166  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ICXBNB' order by id;
167  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RLCBNB' order by id;
168  /  752
169  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ALPACABNB' order by id;
170  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'YFIIBNB' order by id;
171  /  752
172  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'OMGBNB' order by id;
173  /  752
174  /  752
175  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'INJBNB' order by id;
176  /  752
177  /  752
178  /  752
179  /  752
180  /  752
181  /  752
182  /  752
183  /  752
184  /  752
185  /  752
186  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'IRISBNB' order by id;
187  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ALGOBNB' order by id;
188  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MFTBNB' order by id;
189  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XZCBNB' order by id;
190  /  752
191  /  752
192  /  752
193  /  752
194  /  752
195  /  752
196  /  752
197  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BIFIBNB' order by id;
198  /  752
199  /  752
200  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'LTOBNB' order by id;
201  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NEOBNB' order by id;
202  /  752
203  /  752
204  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'LSKBNB' order by id;
205  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TRBBNB' order by id;
206  /  752
207  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AGIBNB' order by id;
208  /  752
209  /  752
210  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MDTBNB' order by id;
211  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'COSBNB' order by id;
212  /  752
213  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WNXMBNB' order by id;
214  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FIDABNB' order by id;
215  /  752
216  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RSRBNB' order by id;
217  /  752
218  /  752
219  /  752
220  /  752
221  /  752
222  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ARBNB' order by id;
223  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BZRXBNB' order by id;
224  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ILVBNB' order by id;

225  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MINABNB' order by id;
226  /  752
227  /  752
228  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'KP3RBNB' order by id;
229  /  752
230  /  752
231  /  752
232  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NUBNB' order by id;
233  /  752
234  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ANKRBNB' order by id;
235  /  752
236  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MBLBNB' order by id;
237  /  752
238  /  752
239  /  752
240  /  752
241  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ZENBNB' order by id;
242  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BEAMBNB' order by id;
243  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SKYBNB' order by id;
244  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XRPBNB' order by id;
245  /  752
246  /  752
247  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'YGGBNB' order by id;
248  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XMRBNB' order by id;
249  /  752
250  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'VTHOBNB' order by id;
251  /  752
252  /  752
253  /  752
254  /  752
255  /  752
256  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CAKEBNB' order by id;
257  /  752
258  /  752
259  /  752
260  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'POWRBNB' order by id;
261  /  752
262  /  752
263  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'VITEBNB' order by id;
264  /  752
265  /  752
266  /  752
267  /  752
268  /  752
269  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ANTBNB' order by id;
270  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PAXGBNB' order by id;
271  /  752
272  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'HBARBNB' order by id;
273  /  752
274  /  752
275  /  752
276  /  752
277  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WTCBNB' order by id;
278  /  752
279  /  752
280  /  752
281  /  752
282  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XEMBNB' order by id;
283  /  752
284  /  752
285  /  752
286  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AVAXBNB' order by id;
287  /  752
288  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SOLBNB' order by id;
289  /  752
290  /  752
291  /  752
292  /  752
293  /  752
294  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BLZBNB' order by id;
295  /  752
296  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'POLSBNB' order by id;
297  /  752
298  /  752
299  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'LTCBNB' order by id;
300  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'QLCBNB' order by id;
301  /  752
302  /  752
303  /  752
304  /  752
305  /  752
306  /  752
307  /  752
308  /  752
309  /  752
310  /  752
311  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'LUNABNB' order by id;
312  /  752
313  /  752
314  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'QUICKBNB' order by id;
315  /  752
316  /  752
317  /  752
318  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AEBNB' order by id;
319  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SANDBNB' order by id;
320  /  752
321  /  752
322  /  752
323  /  752
324  /  752
325  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BATBNB' order by id;
326  /  752
327  /  752
328  /  752
329  /  752
330  /  752
331  /  752
332  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SNXBNB' order by id;
333  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PROMBNB' order by id;
334  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'QTUMBNB' order by id;
335  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NASBNB' order by id;
336  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DREPBNB' order by id;
337  /  752
338  /  752
339  /  752
340  /  752
341  /  752
342  /  752
343  /  752
344  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PERLBNB' order by id;
345  /  752
346  /  752
347  /  752
348  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'COCOSBNB' order by id;
349  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ATABNB' order by id;

350  /  752
351  /  752
352  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CREAMBNB' order by id;
353  /  752
354  /  752
355  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WINBNB' order by id;
356  /  752
357  /  752
358  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WINGBNB' order by id;
359  /  752
360  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ONTBNB' order by id;
361  /  752
362  /  752
363  /  752
364  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RENBNB' order by id;
365  /  752
366  /  752
367  /  752
368  /  752
369  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NULSBNB' order by id;
370  /  752
371  /  752
372  /  752
373  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CHZBNB' order by id;
374  /  752
375  /  752
376  /  752
377  /  752
378  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CTKBNB' order by id;
379  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ZRXBNB' order by id;
380  /  752
381  /  752
382  /  752
383  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DAIBNB' order by id;
384  /  752
385  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'GTCBNB' order by id;
386  /  752
387  /  752
388  /  752
389  /  752
390  /  752
391  /  752
392  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DYDXBNB' order by id;
393  /  752
394  /  752
395  /  752
396  /  752
397  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NMRBNB' order by id;
398  /  752
399  /  752
400  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'HOTBNB' order by id;
401  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BCHBNB' order by id;
402  /  752
403  /  752
404  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FIOBNB' order by id;
405  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TRIGBNB' order by id;
406  /  752
407  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RVNBNB' order by id;
408  /  752
409  /  752
410  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MKRBNB' order by id;
411  /  752
412  /  752
413  /  752
414  /  752
415  /  752
416  /  752
417  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XLMBNB' order by id;
418  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'C98BNB' order by id;
419  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'IQBNB' order by id;
420  /  752
421  /  752
422  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CLVBNB' order by id;
423  /  752
424  /  752
425  /  752
426  /  752
427  /  752
428  /  752
429  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'STXBNB' order by id;
430  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'REPBNB' order by id;
431  /  752
432  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AXSBNB' order by id;
433  /  752
434  /  752
435  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'STEEMBNB' order by id;
436  /  752
437  /  752
438  /  752
439  /  752
440  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DIABNB' order by id;
441  /  752
442  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AMBBNB' order by id;
443  /  752
444  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TFUELBNB' order by id;
445  /  752
446  /  752
447  /  752
448  /  752
449  /  752
450  /  752
451  /  752
452  /  752
453  /  752
454  /  752
455  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NANOBNB' order by id;
456  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'KSMBNB' order by id;
457  /  752
458  /  752
459  /  752
460  /  752
461  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SYSBNB' order by id;
462  /  752
463  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'VENBNB' order by id;
464  /  752
465  /  752
466  /  752
467  /  752
468  /  752
469  /  752
470  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NCASHBNB' order by id;
471  /  752
472  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ADABNB' order by id;
473  /  752
474  /  752
475  /  752
476  /  752
477  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'OSTBNB' order by id;
478  /  752
479  /  752
480  /  752
481  /  752
482  /  752
483  /  752
484  /  752
485  /  752
486  /  752
487  /  752
488  /  752
489  /  752
490  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'STORMBNB' order by id;

491  /  752
492  /  752
493  /  752
494  /  752
495  /  752
496  /  752
497  /  752
498  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RCNBNB' order by id;
499  /  752
500  /  752
501  /  752
502  /  752
503  /  752
504  /  752
505  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FETBNB' order by id;
506  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TCTBNB' order by id;
507  /  752
508  /  752
509  /  752
510  /  752
511  /  752
512  /  752
513  /  752
514  /  752
515  /  752
516  /  752
517  /  752
518  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'POLYBNB' order by id;
519  /  752
520  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'GTOBNB' order by id;
521  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RAYBNB' order by id;
522  /  752
523  /  752
524  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'USDCBNB' order by id;
525  /  752
526  /  752
527  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ATOMBNB' order by id;
528  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'APPCBNB' order by id;
529  /  752
530  /  752
531  /  752
532  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NXSBNB' order by id;
533  /  752
534  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MBOXBNB' order by id;
535  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BAKEBNB' order by id;
536  /  752
537  /  752
538  /  752
539  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WRXBNB' order by id;
540  /  752
541  /  752
542  /  752
543  /  752
544  /  752
545  /  752
546  /  752
547  /  752
548  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'XTZBNB' order by id;
549  /  752
550  /  752
551  /  752
552  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CTSIBNB' order by id;
553  /  752
554  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NKNBNB' order by id;
555  /  752
556  /  752
557  /  752
558  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DGBBNB' order by id;
559  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RUNEBNB' order by id;
560  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'QSPBNB' order by id;
561  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ARPABNB' order by id;
562  /  752
563  /  752
564  /  752
565  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AAVEBNB' order by id;
566  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TROYBNB' order by id;
567  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'KEEPBNB' order by id;
568  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ONGBNB' order by id;
569  /  752
570  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TUSDBNB' order by id;
571  /  752
572  /  752
573  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CMTBNB' order by id;
574  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NEARBNB' order by id;
575  /  752
576  /  752
577  /  752
578  /  752
579  /  752
580  /  752
581  /  752
582  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'YFIBNB' order by id;
583  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FTMBNB' order by id;
584  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'FILBNB' order by id;
585  /  752
586  /  752
587  /  752
588  /  752
589  /  752
590  /  752
591  /  752
592  /  752
593  /  752
594  /  752
595  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'COTIBNB' order by id;
596  /  752
597  /  752
598  /  752
599  /  752
600  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'KLAYBNB' order by id;
601  /  752
602  /  752
603  /  752
604  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MITHBNB' order by id;
605  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SUSHIBNB' order by id;
606  /  752
607  /  752
608  /  752
609  /  752
610  /  752
611  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'STMXBNB' order by id;
612  /  752
613  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CTXCBNB' order by id;
614  /  752
615  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MDXBNB' order by id;
616  /  752
617  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'KAVABNB' order by id;
618  /  752
619  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'SRMBNB' order by id;

620  /  752
621  /  752
622  /  752
623  /  752
624  /  752
625  /  752
626  /  752
627  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AIONBNB' order by id;
628  /  752
629  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BURGERBNB' order by id;
630  /  752
631  /  752
632  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BRDBNB' order by id;
633  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MASKBNB' order by id;
634  /  752
635  /  752
636  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DCRBNB' order by id;
637  /  752
638  /  752
639  /  752
640  /  752
641  /  752
642  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DLTBNB' order by id;
643  /  752
644  /  752
645  /  752
646  /  752
647  /  752
648  /  752
649  /  752
650  /  752
651  /  752
652  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'LOOMBNB' order by id;
653  /  752
654  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BANDBNB' order by id;
655  /  752
656  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TRXBNB' order by id;
657  /  752
658  /  752
659  /  752
660  /  752
661  /  752
662  /  752
663  /  752
664  /  752
665  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BTTBNB' order by id;
666  /  752
667  /  752
668  /  752
669  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'GALABNB' order by id;
670  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'GNOBNB' order by id;
671  /  752
672  /  752
673  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ZECBNB' order by id;
674  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'HIVEBNB' order by id;
675  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ERNBNB' order by id;
676  /  752
677  /  752
678  /  752
679  /  752
680  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ALPHABNB' order by id;
681  /  752
682  /  752
683  /  752
684  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CELRBNB' order by id;
685  /  752
686  /  752
687  /  752
688  /  752
689  /  752
690  /  752
691  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'CRVBNB' order by id;
692  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'UNIBNB' order by id;
693  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MCOBNB' order by id;
694  /  752
695  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'POABNB' order by id;
696  /  752
697  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'TRIBEBNB' order by id;
698  /  752
699  /  752
700  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ETCBNB' order by id;
701  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'OGNBNB' order by id;
702  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'NAVBNB' order by id;
703  /  752
704  /  752
705  /  752
706  /  752
707  /  752
708  /  752
709  /  752
710  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'DOGEBNB' order by id;
711  /  752
712  /  752
713  /  752
714  /  752
715  /  752
716  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'WAXPBNB' order by id;
717  /  752
718  /  752
719  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'RPXBNB' order by id;
720  /  752
721  /  752
722  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BALBNB' order by id;
723  /  752
724  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'AVABNB' order by id;
725  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'ARDRBNB' order by id;
726  /  752
727  /  752
728  /  752
729  /  752
730  /  752
731  /  752
732  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'BELBNB' order by id;
733  /  752
734  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'MATICBNB' order by id;
735  /  752
736  /  752
737  /  752
738  /  752
739  /  752
740  /  752
741  /  752
742  /  752
743  /  752
744  /  752
745  /  752
746  /  752
747  /  752
748  /  752
749  /  752
750  /  752
751  /  752
0  /  752
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM backtesting WHERE symbol like 'PAXBTC' order by id;