In [26]:
#import modules
import json
import pandas as pd
from binance.client import Client
from dotenv import load_dotenv
from envs import env
import time
import re
import os
import datetime
from datetime import timedelta

In [27]:
#import classes from ./ folder
import postgresdbAccess

In [28]:
#read fibonacci retracements  from json
with open('fibLvl.json') as file:
    fibLvl = json.load(file)

In [71]:
def backtest():
    #initiate empty open positions
    openPositions = {}
    #initiate postgresdb class
    postgres = postgresdbAccess.postgresAccess()
    #get unique simbol list
    sql = ("SELECT distinct symbol FROM " + dbTable + ";")
    uniqueSymbol = pd.DataFrame(postgres.sqlQuery(sql))
    uniqueSymbol = uniqueSymbol[0]
    #initiate empty percent bar
    percentBar = 0
    #loop over every symbol in symbol list
    for symbol in uniqueSymbol:
        #print progress
        print(percentBar, " / ", len(uniqueSymbol))
        percentBar = percentBar + 1
        #skip if symbol is not to be considered
        #null askprice is sorted out with crawler already
        if not (symbol.endswith(baseCurrency) and
               len(symbol) < 11):
            continue
        #check if open position was left over from last symbol and simulate close
        if openPositions:
            #prepare sql for close
            openPositions['resultPercent'] = ((row[4] - openPositions['askPrice']) / openPositions['askPrice']) * 100 - brokerFees * 2.55
            openPositions['stopId'] = row[0]
            closeSql = ("UPDATE " + dbTable + " SET" +
            " startId = '" + str(int(openPositions['startId'])) +
            "', fibLevel = '" + str(openPositions['fibLevel']) +
            "', midId = '" + str(int(openPositions['id'])) +
            "', corValue = '" + str(openPositions['corValue']) +
            "', takeProfit = '" + str(openPositions['takeProfit']) +
            "', stopLoss = '" + str(openPositions['stopLoss']) +  
            "', resultpercent = '" + str(openPositions['resultPercent']) +
            "', stopid = '" + str(openPositions['stopId']) +
            "' WHERE id = '" + str(int(openPositions['id'])) +
            "';")
            postgres.sqlUpdate(closeSql)
            openPositions = {}
        #query for every line for symbol
        sql = ("SELECT id, time, symbol, askprice, " +
               "bidprice, highprice, quotevolume, " +
               "pricechangepercent, weightedavgprice, openprice" +
            " FROM " + dbTable + " WHERE" +
            " symbol like '" + symbol + "' order by id;")
        print(sql)
        bigData = pd.DataFrame(postgres.sqlQuery(sql))
        bigData[0] = pd.to_numeric(bigData[0])
        bigData[1] = pd.to_datetime(bigData[1])
        bigData[3] = pd.to_numeric(bigData[3])
        bigData[6] = pd.to_numeric(bigData[6])
        bigData[7] = pd.to_numeric(bigData[7])
        bigData[8] = pd.to_numeric(bigData[8])
        bigData[9] = pd.to_numeric(bigData[9])
        #get start of timedelta
        bigData[5] = bigData[1] - timedelta(hours=33)
        #loop over every row
        for index, row in bigData.iterrows():
            before_start_date = bigData[1] <= row[5]
            if len(bigData.loc[before_start_date]) > 0:
                #get data for consideration
                after_start_date = bigData[1] >= row[5]
                before_end_date = bigData[1] <= row[1]
                between_two_dates = after_start_date & before_end_date
                fibDates = bigData.loc[between_two_dates]
                diff = fibDates[3].max() - fibDates[3].min()
                # calculate fibRetracements
                fibRetracement = pd.DataFrame(fibLvl)
                maxAsk = fibDates[3].max()
                for lvl in fibRetracement:
                    fibRetracement[1] =  maxAsk - diff * fibRetracement[0]
                    fibRetracement[2] = fibRetracement[1] * 0.9995
                    fibRetracement[3] = fibRetracement[1] * 1.0005
                #calculate corvalue
                corValue = fibDates[0].corr(fibDates[3])
                #if an open position exists, check if it can be closed
                if openPositions:
                    if (row[3] < openPositions['stopLoss'] or
                        row[3] > openPositions['takeProfit']):
                        #prepare sql for close
                        openPositions['resultPercent'] = ((row[4] - openPositions['askPrice']) / openPositions['askPrice']) * 100 - brokerFees * 3.5
                        openPositions['stopId'] = row[0]
                        closeSql = ("UPDATE " + dbTable + " SET" +
                        " startId = '" + str(int(openPositions['startId'])) +
                        "', fibLevel = '" + str(openPositions['fibLevel']) +
                        "', midId = '" + str(int(openPositions['id'])) +
                        "', corValue = '" + str(openPositions['corValue']) +
                        "', takeProfit = '" + str(openPositions['takeProfit']) +
                        "', stopLoss = '" + str(openPositions['stopLoss']) +  
                        "', resultpercent = '" + str(openPositions['resultPercent']) +
                        "', stopid = '" + str(openPositions['stopId']) +
                        "' WHERE id = '" + str(int(openPositions['id'])) +
                        "';")
                        #update database
                        postgres.sqlUpdate(closeSql)
                        #clear open position
                        openPositions = {}
                else:
                    #loop over considered fibonacciretracements
                    for i in [7]:
                        #check if buy requirements are met
                        if (corValue > 0.5 and
                            row[3] < fibRetracement[3][i] and
                            row[3] > fibRetracement[2][i]):
                            openPositions['startId'] = fibDates[0].min()
                            openPositions['id'] = row[0]
                            openPositions['bidPrice'] = row[4]
                            openPositions['fibLevel'] = i
                            openPositions['symbol'] = symbol
                            openPositions['askPrice'] = row[3]
                            openPositions['corValue'] = corValue
                            openPositions['takeProfit'] = fibRetracement[3][i+4]
                            openPositions['stopLoss'] = fibRetracement[2][i-1]
    #close database connection
    postgres.databaseClose()

In [73]:
testTables = [{"table":"bnbtesting","currency":"BNB"}]
             #{"table":"btctesting","currency":"BTC"},
             #{"table":"ethtesting","currency":"ETH"}]
for iteration in testTables:
    load_dotenv('../.env')
    try:
        liveVolume=env("liveVolume")
        apiSecret=env('apiSecret')
        apiKey=env('apiKey')
        dbTable=iteration["table"]
        baseCurrency=iteration["currency"]
        brokerFees=float(env('brokerFees'))
        liveTrading=env("liveTrading", 'False').lower() in ('true', '1', 't')
    except KeyError:
        print("No env variables set.")
        sys.exit(1)
    client = Client(apiKey, apiSecret, {'timeout':600})
    backtest()

0  /  1551
1  /  1551
2  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CNDBNB' order by id;
3  /  1551
4  /  1551
5  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'YOYOBNB' order by id;
6  /  1551
7  /  1551
8  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FTTBNB' order by id;
9  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'OCEANBNB' order by id;
10  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'COMPBNB' order by id;
11  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BCPTBNB' order by id;
12  /  1551
13  /  1551
14  /  1551
15  /  1551
16  /  1551
17  /  1551
18  /  1551
19  /  1551
20  /  1551
21  /  1551
22  /  1551
23  /  1551
24  /  1551
25  /  1551
26  /  1551
27  /  1551
28  /  1551
29  /  1551
30  /  1551
31  /  1551
32  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PAXBNB' order by id;
33  /  1551
34  /  1551
35  /  1551
36  /  1551
37  /  1551
38  /  1551
39  /  1551
40  /  1551
41  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DASHBNB' order by id;
42  /  1551
43  /  1551
44  /  1551
45  /  1551
46  /  1551
47  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TOMOBNB' order by id;
48  /  1551
49  /  1551
50  /  1551
51  /  1551
52  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'EOSBNB' order by id;
53  /  1551
54  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'LPTBNB' order by id;
55  /  1551
56  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SPARTABNB' order by id;
57  /  1551
58  /  1551
59  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'THETABNB' order by id;
60  /  1551
61  /  1551
62  /  1551
63  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SXPBNB' order by id;
64  /  1551
65  /  1551
66  /  1551
67  /  1551
68  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'VETBNB' order by id;
69  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'IOTABNB' order by id;
70  /  1551
71  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DUSKBNB' order by id;
72  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SCBNB' order by id;
73  /  1551
74  /  1551
75  /  1551
76  /  1551
77  /  1551
78  /  1551
79  /  1551
80  /  1551
81  /  1551
82  /  1551
83  /  1551
84  /  1551
85  /  1551
86  /  1551
87  /  1551
88  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CHRBNB' order by id;
89  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'STPTBNB' order by id;
90  /  1551
91  /  1551
92  /  1551
93  /  1551
94  /  1551
95  /  1551
96  /  1551
97  /  1551
98  /  1551
99  /  1551
100  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TORNBNB' order by id;
101  /  1551
102  /  1551
103  /  1551
104  /  1551
105  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XVSBNB' order by id;
106  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FLMBNB' order by id;
107  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MLNBNB' order by id;
108  /  1551
109  /  1551
110  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SWRVBNB' order by id;
111  /  1551
112  /  1551
113  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DOTBNB' order by id;
114  /  1551
115  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'GNTBNB' order by id;
116  /  1551
117  /  1551
118  /  1551
119  /  1551
120  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PHBBNB' order by id;
121  /  1551
122  /  1551
123  /  1551
124  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WABIBNB' order by id;
125  /  1551
126  /  1551
127  /  1551
128  /  1551
129  /  1551
130  /  1551
131  /  1551
132  /  1551
133  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'HARDBNB' order by id;
134  /  1551
135  /  1551
136  /  1551
137  /  1551
138  /  1551
139  /  1551
140  /  1551
141  /  1551
142  /  1551
143  /  1551
144  /  1551
145  /  1551
146  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'STRATBNB' order by id;
147  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'VIABNB' order by id;
148  /  1551
149  /  1551
150  /  1551
151  /  1551
152  /  1551
153  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RLCBNB' order by id;
154  /  1551
155  /  1551
156  /  1551
157  /  1551
158  /  1551
159  /  1551
160  /  1551
161  /  1551
162  /  1551
163  /  1551
164  /  1551
165  /  1551
166  /  1551
167  /  1551
168  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'IRISBNB' order by id;
169  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ALGOBNB' order by id;
170  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XZCBNB' order by id;

171  /  1551
172  /  1551
173  /  1551
174  /  1551
175  /  1551
176  /  1551
177  /  1551
178  /  1551
179  /  1551
180  /  1551
181  /  1551
182  /  1551
183  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'LTOBNB' order by id;
184  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NEOBNB' order by id;
185  /  1551
186  /  1551
187  /  1551
188  /  1551
189  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TRBBNB' order by id;
190  /  1551
191  /  1551
192  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AGIBNB' order by id;
193  /  1551
194  /  1551
195  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MDTBNB' order by id;
196  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WNXMBNB' order by id;
197  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RSRBNB' order by id;
198  /  1551
199  /  1551
200  /  1551
201  /  1551
202  /  1551
203  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BZRXBNB' order by id;
204  /  1551
205  /  1551
206  /  1551
207  /  1551
208  /  1551
209  /  1551
210  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ANKRBNB' order by id;
211  /  1551
212  /  1551
213  /  1551
214  /  1551
215  /  1551
216  /  1551
217  /  1551
218  /  1551
219  /  1551
220  /  1551
221  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BEAMBNB' order by id;
222  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XRPBNB' order by id;
223  /  1551
224  /  1551
225  /  1551
226  /  1551
227  /  1551
228  /  1551
229  /  1551
230  /  1551
231  /  1551
232  /  1551
233  /  1551
234  /  1551
235  /  1551
236  /  1551
237  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'POWRBNB' order by id;
238  /  1551
239  /  1551
240  /  1551
241  /  1551
242  /  1551
243  /  1551
244  /  1551
245  /  1551
246  /  1551
247  /  1551
248  /  1551
249  /  1551
250  /  1551
251  /  1551
252  /  1551
253  /  1551
254  /  1551
255  /  1551
256  /  1551
257  /  1551
258  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SOLBNB' order by id;
259  /  1551
260  /  1551
261  /  1551
262  /  1551
263  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BLZBNB' order by id;
264  /  1551
265  /  1551
266  /  1551
267  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'POLSBNB' order by id;
268  /  1551
269  /  1551
270  /  1551
271  /  1551
272  /  1551
273  /  1551
274  /  1551
275  /  1551
276  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'QLCBNB' order by id;
277  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'LTCBNB' order by id;
278  /  1551
279  /  1551
280  /  1551
281  /  1551
282  /  1551
283  /  1551
284  /  1551
285  /  1551
286  /  1551
287  /  1551
288  /  1551
289  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'LUNABNB' order by id;
290  /  1551
291  /  1551
292  /  1551
293  /  1551
294  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SANDBNB' order by id;
295  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AEBNB' order by id;
296  /  1551
297  /  1551
298  /  1551
299  /  1551
300  /  1551
301  /  1551
302  /  1551
303  /  1551
304  /  1551
305  /  1551
306  /  1551
307  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SNXBNB' order by id;
308  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PROMBNB' order by id;
309  /  1551
310  /  1551
311  /  1551
312  /  1551
313  /  1551
314  /  1551
315  /  1551
316  /  1551
317  /  1551
318  /  1551
319  /  1551
320  /  1551
321  /  1551
322  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CREAMBNB' order by id;
323  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WINBNB' order by id;
324  /  1551
325  /  1551
326  /  1551
327  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ONTBNB' order by id;
328  /  1551
329  /  1551
330  /  1551
331  /  1551
332  /  1551
333  /  1551
334  /  1551
335  /  1551
336  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RENBNB' order by id;
337  /  1551
338  /  1551
339  /  1551
340  /  1551
341  /  1551
342  /  1551
343  /  1551
344  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CHZBNB' order by id;
345  /  1551
346  /  1551
347  /  1551
348  /  1551
349  /  1551
350  /  1551
351  /  1551
352  /  1551
353  /  1551
354  /  1551
355  /  1551
356  /  1551
357  /  1551
358  /  1551
359  /  1551
360  /  1551
361  /  1551
362  /  1551
363  /  1551
364  /  1551
365  /  1551
366  /  1551
367  /  1551
368  /  1551
369  /  1551
370  /  1551
371  /  1551
372  /  1551
373  /  1551
374  /  1551
375  /  1551
376  /  1551
377  /  1551
378  /  1551
379  /  1551
380  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FIOBNB' order by id;
381  /  1551
382  /  1551
383  /  1551
384  /  1551
385  /  1551
386  /  1551
387  /  1551
388  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MKRBNB' order by id;
389  /  1551
390  /  1551
391  /  1551
392  /  1551
393  /  1551
394  /  1551
395  /  1551
396  /  1551
397  /  1551
398  /  1551
399  /  1551
400  /  1551
401  /  1551
402  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'C98BNB' order by id;

403  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'IQBNB' order by id;
404  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XLMBNB' order by id;
405  /  1551
406  /  1551
407  /  1551
408  /  1551
409  /  1551
410  /  1551
411  /  1551
412  /  1551
413  /  1551
414  /  1551
415  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AXSBNB' order by id;
416  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'REPBNB' order by id;
417  /  1551
418  /  1551
419  /  1551
420  /  1551
421  /  1551
422  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'STEEMBNB' order by id;
423  /  1551
424  /  1551
425  /  1551
426  /  1551
427  /  1551
428  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DIABNB' order by id;
429  /  1551
430  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AMBBNB' order by id;
431  /  1551
432  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TFUELBNB' order by id;
433  /  1551
434  /  1551
435  /  1551
436  /  1551
437  /  1551
438  /  1551
439  /  1551
440  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'KSMBNB' order by id;
441  /  1551
442  /  1551
443  /  1551
444  /  1551
445  /  1551
446  /  1551
447  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SYSBNB' order by id;
448  /  1551
449  /  1551
450  /  1551
451  /  1551
452  /  1551
453  /  1551
454  /  1551
455  /  1551
456  /  1551
457  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ADABNB' order by id;
458  /  1551
459  /  1551
460  /  1551
461  /  1551
462  /  1551
463  /  1551
464  /  1551
465  /  1551
466  /  1551
467  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'OSTBNB' order by id;
468  /  1551
469  /  1551
470  /  1551
471  /  1551
472  /  1551
473  /  1551
474  /  1551
475  /  1551
476  /  1551
477  /  1551
478  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'STORMBNB' order by id;
479  /  1551
480  /  1551
481  /  1551
482  /  1551
483  /  1551
484  /  1551
485  /  1551
486  /  1551
487  /  1551
488  /  1551
489  /  1551
490  /  1551
491  /  1551
492  /  1551
493  /  1551
494  /  1551
495  /  1551
496  /  1551
497  /  1551
498  /  1551
499  /  1551
500  /  1551
501  /  1551
502  /  1551
503  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'POLYBNB' order by id;
504  /  1551
505  /  1551
506  /  1551
507  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'GTOBNB' order by id;
508  /  1551
509  /  1551
510  /  1551
511  /  1551
512  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'USDCBNB' order by id;
513  /  1551
514  /  1551
515  /  1551
516  /  1551
517  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'APPCBNB' order by id;
518  /  1551
519  /  1551
520  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NXSBNB' order by id;
521  /  1551
522  /  1551
523  /  1551
524  /  1551
525  /  1551
526  /  1551
527  /  1551
528  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WRXBNB' order by id;
529  /  1551
530  /  1551
531  /  1551
532  /  1551
533  /  1551
534  /  1551
535  /  1551
536  /  1551
537  /  1551
538  /  1551
539  /  1551
540  /  1551
541  /  1551
542  /  1551
543  /  1551
544  /  1551
545  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CTSIBNB' order by id;
546  /  1551
547  /  1551
548  /  1551
549  /  1551
550  /  1551
551  /  1551
552  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DGBBNB' order by id;
553  /  1551
554  /  1551
555  /  1551
556  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ARPABNB' order by id;
557  /  1551
558  /  1551
559  /  1551
560  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TROYBNB' order by id;
561  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ONGBNB' order by id;
562  /  1551
563  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TUSDBNB' order by id;
564  /  1551
565  /  1551
566  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CMTBNB' order by id;
567  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NEARBNB' order by id;
568  /  1551
569  /  1551
570  /  1551
571  /  1551
572  /  1551
573  /  1551
574  /  1551
575  /  1551
576  /  1551
577  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'YFIBNB' order by id;
578  /  1551
579  /  1551
580  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FTMBNB' order by id;
581  /  1551
582  /  1551
583  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FILBNB' order by id;
584  /  1551
585  /  1551
586  /  1551
587  /  1551
588  /  1551
589  /  1551
590  /  1551
591  /  1551
592  /  1551
593  /  1551
594  /  1551
595  /  1551
596  /  1551
597  /  1551
598  /  1551
599  /  1551
600  /  1551
601  /  1551
602  /  1551
603  /  1551
604  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MITHBNB' order by id;
605  /  1551
606  /  1551
607  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'STMXBNB' order by id;

608  /  1551
609  /  1551
610  /  1551
611  /  1551
612  /  1551
613  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'KAVABNB' order by id;
614  /  1551
615  /  1551
616  /  1551
617  /  1551
618  /  1551
619  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AIONBNB' order by id;
620  /  1551
621  /  1551
622  /  1551
623  /  1551
624  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MASKBNB' order by id;
625  /  1551
626  /  1551
627  /  1551
628  /  1551
629  /  1551
630  /  1551
631  /  1551
632  /  1551
633  /  1551
634  /  1551
635  /  1551
636  /  1551
637  /  1551
638  /  1551
639  /  1551
640  /  1551
641  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BANDBNB' order by id;
642  /  1551
643  /  1551
644  /  1551
645  /  1551
646  /  1551
647  /  1551
648  /  1551
649  /  1551
650  /  1551
651  /  1551
652  /  1551
653  /  1551
654  /  1551
655  /  1551
656  /  1551
657  /  1551
658  /  1551
659  /  1551
660  /  1551
661  /  1551
662  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'HIVEBNB' order by id;
663  /  1551
664  /  1551
665  /  1551
666  /  1551
667  /  1551
668  /  1551
669  /  1551
670  /  1551
671  /  1551
672  /  1551
673  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ALPHABNB' order by id;
674  /  1551
675  /  1551
676  /  1551
677  /  1551
678  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CELRBNB' order by id;
679  /  1551
680  /  1551
681  /  1551
682  /  1551
683  /  1551
684  /  1551
685  /  1551
686  /  1551
687  /  1551
688  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CRVBNB' order by id;
689  /  1551
690  /  1551
691  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MCOBNB' order by id;
692  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'POABNB' order by id;
693  /  1551
694  /  1551
695  /  1551
696  /  1551
697  /  1551
698  /  1551
699  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ETCBNB' order by id;
700  /  1551
701  /  1551
702  /  1551
703  /  1551
704  /  1551
705  /  1551
706  /  1551
707  /  1551
708  /  1551
709  /  1551
710  /  1551
711  /  1551
712  /  1551
713  /  1551
714  /  1551
715  /  1551
716  /  1551
717  /  1551
718  /  1551
719  /  1551
720  /  1551
721  /  1551
722  /  1551
723  /  1551
724  /  1551
725  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RPXBNB' order by id;
726  /  1551
727  /  1551
728  /  1551
729  /  1551
730  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AVABNB' order by id;
731  /  1551
732  /  1551
733  /  1551
734  /  1551
735  /  1551
736  /  1551
737  /  1551
738  /  1551
739  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BELBNB' order by id;
740  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MATICBNB' order by id;
741  /  1551
742  /  1551
743  /  1551
744  /  1551
745  /  1551
746  /  1551
747  /  1551
748  /  1551
749  /  1551
750  /  1551
751  /  1551
752  /  1551
753  /  1551
754  /  1551
755  /  1551
756  /  1551
757  /  1551
758  /  1551
759  /  1551
760  /  1551
761  /  1551
762  /  1551
763  /  1551
764  /  1551
765  /  1551
766  /  1551
767  /  1551
768  /  1551
769  /  1551
770  /  1551
771  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ADXBNB' order by id;
772  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ENJBNB' order by id;
773  /  1551
774  /  1551
775  /  1551
776  /  1551
777  /  1551
778  /  1551
779  /  1551
780  /  1551
781  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WANBNB' order by id;
782  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RDNBNB' order by id;
783  /  1551
784  /  1551
785  /  1551
786  /  1551
787  /  1551
788  /  1551
789  /  1551
790  /  1551
791  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'IOSTBNB' order by id;
792  /  1551
793  /  1551
794  /  1551
795  /  1551
796  /  1551
797  /  1551
798  /  1551
799  /  1551
800  /  1551
801  /  1551
802  /  1551
803  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BONDBNB' order by id;
804  /  1551
805  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'UNFIBNB' order by id;
806  /  1551
807  /  1551
808  /  1551
809  /  1551
810  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NEBLBNB' order by id;
811  /  1551
812  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ICPBNB' order by id;
813  /  1551
814  /  1551
815  /  1551
816  /  1551
817  /  1551
818  /  1551
819  /  1551
820  /  1551
821  /  1551
822  /  1551
823  /  1551
824  /  1551
825  /  1551
826  /  1551
827  /  1551
828  /  1551
829  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FLOWBNB' order by id;
830  /  1551
831  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PIVXBNB' order by id;
832  /  1551
833  /  1551
834  /  1551
835  /  1551
836  /  1551
837  /  1551
838  /  1551
839  /  1551
840  /  1551
841  /  1551
842  /  1551
843  /  1551
844  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WAVESBNB' order by id;
845  /  1551
846  /  1551
847  /  1551
848  /  1551
849  /  1551
850  /  1551
851  /  1551
852  /  1551
853  /  1551
854  /  1551
855  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'QNTBNB' order by id;
856  /  1551
857  /  1551
858  /  1551
859  /  1551
860  /  1551
861  /  1551
862  /  1551
863  /  1551
864  /  1551
865  /  1551
866  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BTSBNB' order by id;

867  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'GOBNB' order by id;
868  /  1551
869  /  1551
870  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ERDBNB' order by id;
871  /  1551
872  /  1551
873  /  1551
874  /  1551
875  /  1551
876  /  1551
877  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ZILBNB' order by id;
878  /  1551
879  /  1551
880  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PHXBNB' order by id;
881  /  1551
882  /  1551
883  /  1551
884  /  1551
885  /  1551
886  /  1551
887  /  1551
888  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'EGLDBNB' order by id;
889  /  1551
890  /  1551
891  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BCCBNB' order by id;
892  /  1551
893  /  1551
894  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CVCBNB' order by id;
895  /  1551
896  /  1551
897  /  1551
898  /  1551
899  /  1551
900  /  1551
901  /  1551
902  /  1551
903  /  1551
904  /  1551
905  /  1551
906  /  1551
907  /  1551
908  /  1551
909  /  1551
910  /  1551
911  /  1551
912  /  1551
913  /  1551
914  /  1551
915  /  1551
916  /  1551
917  /  1551
918  /  1551
919  /  1551
920  /  1551
921  /  1551
922  /  1551
923  /  1551
924  /  1551
925  /  1551
926  /  1551
927  /  1551
928  /  1551
929  /  1551
930  /  1551
931  /  1551
932  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ONEBNB' order by id;
933  /  1551
934  /  1551
935  /  1551
936  /  1551
937  /  1551
938  /  1551
939  /  1551
940  /  1551
941  /  1551
942  /  1551
943  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BCNBNB' order by id;
944  /  1551
945  /  1551
946  /  1551
947  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ICXBNB' order by id;
948  /  1551
949  /  1551
950  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'YFIIBNB' order by id;
951  /  1551
952  /  1551
953  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'OMGBNB' order by id;
954  /  1551
955  /  1551
956  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'INJBNB' order by id;
957  /  1551
958  /  1551
959  /  1551
960  /  1551
961  /  1551
962  /  1551
963  /  1551
964  /  1551
965  /  1551
966  /  1551
967  /  1551
968  /  1551
969  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MFTBNB' order by id;
970  /  1551
971  /  1551
972  /  1551
973  /  1551
974  /  1551
975  /  1551
976  /  1551
977  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BIFIBNB' order by id;
978  /  1551
979  /  1551
980  /  1551
981  /  1551
982  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'LSKBNB' order by id;
983  /  1551
984  /  1551
985  /  1551
986  /  1551
987  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'COSBNB' order by id;
988  /  1551
989  /  1551
990  /  1551
991  /  1551
992  /  1551
993  /  1551
994  /  1551
995  /  1551
996  /  1551
997  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ARBNB' order by id;
998  /  1551
999  /  1551
1000  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'KP3RBNB' order by id;
1001  /  1551
1002  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NUBNB' order by id;
1003  /  1551
1004  /  1551
1005  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MBLBNB' order by id;
1006  /  1551
1007  /  1551
1008  /  1551
1009  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SKYBNB' order by id;
1010  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ZENBNB' order by id;
1011  /  1551
1012  /  1551
1013  /  1551
1014  /  1551
1015  /  1551
1016  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XMRBNB' order by id;
1017  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'VTHOBNB' order by id;
1018  /  1551
1019  /  1551
1020  /  1551
1021  /  1551
1022  /  1551
1023  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CAKEBNB' order by id;
1024  /  1551
1025  /  1551
1026  /  1551
1027  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'VITEBNB' order by id;
1028  /  1551
1029  /  1551
1030  /  1551
1031  /  1551
1032  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ANTBNB' order by id;
1033  /  1551
1034  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PAXGBNB' order by id;
1035  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'HBARBNB' order by id;
1036  /  1551
1037  /  1551
1038  /  1551
1039  /  1551
1040  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WTCBNB' order by id;
1041  /  1551
1042  /  1551
1043  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XEMBNB' order by id;
1044  /  1551
1045  /  1551
1046  /  1551
1047  /  1551
1048  /  1551
1049  /  1551
1050  /  1551
1051  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AVAXBNB' order by id;
1052  /  1551
1053  /  1551
1054  /  1551
1055  /  1551
1056  /  1551
1057  /  1551
1058  /  1551
1059  /  1551
1060  /  1551
1061  /  1551
1062  /  1551
1063  /  1551
1064  /  1551
1065  /  1551
1066  /  1551
1067  /  1551
1068  /  1551
1069  /  1551
1070  /  1551
1071  /  1551
1072  /  1551
1073  /  1551
1074  /  1551
1075  /  1551
1076  /  1551
1077  /  1551
1078  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'QUICKBNB' order by id;

1079  /  1551
1080  /  1551
1081  /  1551
1082  /  1551
1083  /  1551
1084  /  1551
1085  /  1551
1086  /  1551
1087  /  1551
1088  /  1551
1089  /  1551
1090  /  1551
1091  /  1551
1092  /  1551
1093  /  1551
1094  /  1551
1095  /  1551
1096  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BATBNB' order by id;
1097  /  1551
1098  /  1551
1099  /  1551
1100  /  1551
1101  /  1551
1102  /  1551
1103  /  1551
1104  /  1551
1105  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'QTUMBNB' order by id;
1106  /  1551
1107  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DREPBNB' order by id;
1108  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NASBNB' order by id;
1109  /  1551
1110  /  1551
1111  /  1551
1112  /  1551
1113  /  1551
1114  /  1551
1115  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'PERLBNB' order by id;
1116  /  1551
1117  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'COCOSBNB' order by id;
1118  /  1551
1119  /  1551
1120  /  1551
1121  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ATABNB' order by id;
1122  /  1551
1123  /  1551
1124  /  1551
1125  /  1551
1126  /  1551
1127  /  1551
1128  /  1551
1129  /  1551
1130  /  1551
1131  /  1551
1132  /  1551
1133  /  1551
1134  /  1551
1135  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'WINGBNB' order by id;
1136  /  1551
1137  /  1551
1138  /  1551
1139  /  1551
1140  /  1551
1141  /  1551
1142  /  1551
1143  /  1551
1144  /  1551
1145  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NULSBNB' order by id;
1146  /  1551
1147  /  1551
1148  /  1551
1149  /  1551
1150  /  1551
1151  /  1551
1152  /  1551
1153  /  1551
1154  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CTKBNB' order by id;
1155  /  1551
1156  /  1551
1157  /  1551
1158  /  1551
1159  /  1551
1160  /  1551
1161  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ZRXBNB' order by id;
1162  /  1551
1163  /  1551
1164  /  1551
1165  /  1551
1166  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DAIBNB' order by id;
1167  /  1551
1168  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'GTCBNB' order by id;
1169  /  1551
1170  /  1551
1171  /  1551
1172  /  1551
1173  /  1551
1174  /  1551
1175  /  1551
1176  /  1551
1177  /  1551
1178  /  1551
1179  /  1551
1180  /  1551
1181  /  1551
1182  /  1551
1183  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NMRBNB' order by id;
1184  /  1551
1185  /  1551
1186  /  1551
1187  /  1551
1188  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'HOTBNB' order by id;
1189  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BCHBNB' order by id;
1190  /  1551
1191  /  1551
1192  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TRIGBNB' order by id;
1193  /  1551
1194  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RVNBNB' order by id;
1195  /  1551
1196  /  1551
1197  /  1551
1198  /  1551
1199  /  1551
1200  /  1551
1201  /  1551
1202  /  1551
1203  /  1551
1204  /  1551
1205  /  1551
1206  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CLVBNB' order by id;
1207  /  1551
1208  /  1551
1209  /  1551
1210  /  1551
1211  /  1551
1212  /  1551
1213  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'STXBNB' order by id;
1214  /  1551
1215  /  1551
1216  /  1551
1217  /  1551
1218  /  1551
1219  /  1551
1220  /  1551
1221  /  1551
1222  /  1551
1223  /  1551
1224  /  1551
1225  /  1551
1226  /  1551
1227  /  1551
1228  /  1551
1229  /  1551
1230  /  1551
1231  /  1551
1232  /  1551
1233  /  1551
1234  /  1551
1235  /  1551
1236  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NANOBNB' order by id;
1237  /  1551
1238  /  1551
1239  /  1551
1240  /  1551
1241  /  1551
1242  /  1551
1243  /  1551
1244  /  1551
1245  /  1551
1246  /  1551
1247  /  1551
1248  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'VENBNB' order by id;
1249  /  1551
1250  /  1551
1251  /  1551
1252  /  1551
1253  /  1551
1254  /  1551
1255  /  1551
1256  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NCASHBNB' order by id;
1257  /  1551
1258  /  1551
1259  /  1551
1260  /  1551
1261  /  1551
1262  /  1551
1263  /  1551
1264  /  1551
1265  /  1551
1266  /  1551
1267  /  1551
1268  /  1551
1269  /  1551
1270  /  1551
1271  /  1551
1272  /  1551
1273  /  1551
1274  /  1551
1275  /  1551
1276  /  1551
1277  /  1551
1278  /  1551
1279  /  1551
1280  /  1551
1281  /  1551
1282  /  1551
1283  /  1551
1284  /  1551
1285  /  1551
1286  /  1551
1287  /  1551
1288  /  1551
1289  /  1551
1290  /  1551
1291  /  1551
1292  /  1551
1293  /  1551
1294  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RCNBNB' order by id;
1295  /  1551
1296  /  1551
1297  /  1551
1298  /  1551
1299  /  1551
1300  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'FETBNB' order by id;
1301  /  1551
1302  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TCTBNB' order by id;
1303  /  1551
1304  /  1551
1305  /  1551
1306  /  1551
1307  /  1551
1308  /  1551
1309  /  1551
1310  /  1551
1311  /  1551
1312  /  1551
1313  /  1551
1314  /  1551
1315  /  1551
1316  /  1551
1317  /  1551
1318  /  1551
1319  /  1551
1320  /  1551
1321  /  1551
1322  /  1551
1323  /  1551
1324  /  1551
1325  /  1551
1326  /  1551
1327  /  1551
1328  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ATOMBNB' order by id;
1329  /  1551
1330  /  1551
1331  /  1551
1332  /  1551
1333  /  1551
1334  /  1551
1335  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BAKEBNB' order by id;

1336  /  1551
1337  /  1551
1338  /  1551
1339  /  1551
1340  /  1551
1341  /  1551
1342  /  1551
1343  /  1551
1344  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'XTZBNB' order by id;
1345  /  1551
1346  /  1551
1347  /  1551
1348  /  1551
1349  /  1551
1350  /  1551
1351  /  1551
1352  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NKNBNB' order by id;
1353  /  1551
1354  /  1551
1355  /  1551
1356  /  1551
1357  /  1551
1358  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'RUNEBNB' order by id;
1359  /  1551
1360  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'QSPBNB' order by id;
1361  /  1551
1362  /  1551
1363  /  1551
1364  /  1551
1365  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'AAVEBNB' order by id;
1366  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'KEEPBNB' order by id;
1367  /  1551
1368  /  1551
1369  /  1551
1370  /  1551
1371  /  1551
1372  /  1551
1373  /  1551
1374  /  1551
1375  /  1551
1376  /  1551
1377  /  1551
1378  /  1551
1379  /  1551
1380  /  1551
1381  /  1551
1382  /  1551
1383  /  1551
1384  /  1551
1385  /  1551
1386  /  1551
1387  /  1551
1388  /  1551
1389  /  1551
1390  /  1551
1391  /  1551
1392  /  1551
1393  /  1551
1394  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'COTIBNB' order by id;
1395  /  1551
1396  /  1551
1397  /  1551
1398  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'KLAYBNB' order by id;
1399  /  1551
1400  /  1551
1401  /  1551
1402  /  1551
1403  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SUSHIBNB' order by id;
1404  /  1551
1405  /  1551
1406  /  1551
1407  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'CTXCBNB' order by id;
1408  /  1551
1409  /  1551
1410  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'MDXBNB' order by id;
1411  /  1551
1412  /  1551
1413  /  1551
1414  /  1551
1415  /  1551
1416  /  1551
1417  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'SRMBNB' order by id;
1418  /  1551
1419  /  1551
1420  /  1551
1421  /  1551
1422  /  1551
1423  /  1551
1424  /  1551
1425  /  1551
1426  /  1551
1427  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BURGERBNB' order by id;
1428  /  1551
1429  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BRDBNB' order by id;
1430  /  1551
1431  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DCRBNB' order by id;
1432  /  1551
1433  /  1551
1434  /  1551
1435  /  1551
1436  /  1551
1437  /  1551
1438  /  1551
1439  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DLTBNB' order by id;
1440  /  1551
1441  /  1551
1442  /  1551
1443  /  1551
1444  /  1551
1445  /  1551
1446  /  1551
1447  /  1551
1448  /  1551
1449  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'LOOMBNB' order by id;
1450  /  1551
1451  /  1551
1452  /  1551
1453  /  1551
1454  /  1551
1455  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'TRXBNB' order by id;
1456  /  1551
1457  /  1551
1458  /  1551
1459  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BTTBNB' order by id;
1460  /  1551
1461  /  1551
1462  /  1551
1463  /  1551
1464  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ZECBNB' order by id;
1465  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ERNBNB' order by id;
1466  /  1551
1467  /  1551
1468  /  1551
1469  /  1551
1470  /  1551
1471  /  1551
1472  /  1551
1473  /  1551
1474  /  1551
1475  /  1551
1476  /  1551
1477  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'UNIBNB' order by id;
1478  /  1551
1479  /  1551
1480  /  1551
1481  /  1551
1482  /  1551
1483  /  1551
1484  /  1551
1485  /  1551
1486  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'OGNBNB' order by id;
1487  /  1551
1488  /  1551
1489  /  1551
1490  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'NAVBNB' order by id;
1491  /  1551
1492  /  1551
1493  /  1551
1494  /  1551
1495  /  1551
1496  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'DOGEBNB' order by id;
1497  /  1551
1498  /  1551
1499  /  1551
1500  /  1551
1501  /  1551
1502  /  1551
1503  /  1551
1504  /  1551
1505  /  1551
1506  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'BALBNB' order by id;
1507  /  1551
1508  /  1551
1509  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'ARDRBNB' order by id;
1510  /  1551
1511  /  1551
1512  /  1551
1513  /  1551
1514  /  1551
1515  /  1551
1516  /  1551
1517  /  1551
1518  /  1551
1519  /  1551
1520  /  1551
1521  /  1551
1522  /  1551
1523  /  1551
1524  /  1551
1525  /  1551
1526  /  1551
1527  /  1551
1528  /  1551
1529  /  1551
1530  /  1551
1531  /  1551
1532  /  1551
1533  /  1551
1534  /  1551
1535  /  1551
1536  /  1551
1537  /  1551
1538  /  1551
1539  /  1551
1540  /  1551
1541  /  1551
1542  /  1551
1543  /  1551
SELECT id, time, symbol, askprice, bidprice, highprice, quotevolume, pricechangepercent, weightedavgprice, openprice FROM bnbtesting WHERE symbol like 'JSTBNB' order by id;
1544  /  1551
1545  /  1551
1546  /  1551
1547  /  1551
1548  /  1551
1549  /  1551
1550  /  1551